-- Database QuanLyBanHang
USE QuanLyBanHang;

-- III
-- 1
SELECT MASP, TENSP FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

-- 2
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN ('cay', 'quyen');

-- 3
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01';

-- 4
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000;

-- 5
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX IN ('Trung Quoc', 'Thai Lan') AND GIA BETWEEN 30000 AND 40000;

-- 6
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD IN ('2007-01-01', '2007-01-02');

-- 7
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD BETWEEN '2007-01-01' AND '2007-01-31'
ORDER BY NGHD ASC, TRIGIA DESC;

-- 8
SELECT DISTINCT KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM HOADON
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE NGHD = '2007-01-01';

-- 9
SELECT HOADON.SOHD, HOADON.TRIGIA
FROM HOADON
JOIN NHANVIEN ON HOADON.MANV = NHANVIEN.MANV
WHERE NHANVIEN.HOTEN = 'Nguyen Van B' AND HOADON.NGHD = '2006-10-28';

-- 10
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE KHACHHANG.HOTEN = 'Nguyen Van A' AND NGHD BETWEEN '2006-10-01' AND '2006-10-31';

-- 11
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP IN ('BB01', 'BB02');