-- Database QuanLyGiaoVu
USE QuanLyGiaoVu;

-- III
-- 1
SELECT H.MAHV, H.HO + ' ' + H.TEN AS HOTEN, H.NGSINH, H.MALOP
FROM HOCVIEN H
JOIN LOP L ON H.MAHV = L.TRGLOP;

-- 2
SELECT H.MAHV, H.HO + ' ' + H.TEN AS HOTEN, K.LANTHI, K.DIEM
FROM KETQUATHI K
JOIN HOCVIEN H ON K.MAHV = H.MAHV
WHERE K.MAMH = 'CTRR' AND H.MALOP = 'K12'
ORDER BY H.HO, H.TEN;

-- 3
SELECT H.MAHV, H.HO + ' ' + H.TEN AS HOTEN, K.MAMH
FROM HOCVIEN H
JOIN KETQUATHI K ON H.MAHV = K.MAHV
WHERE K.LANTHI = 1 AND K.KQUA = 'Dat';

-- 4
SELECT H.MAHV, H.HO + ' ' + H.TEN AS HOTEN
FROM HOCVIEN H
JOIN KETQUATHI K ON H.MAHV = K.MAHV
WHERE K.MAMH = 'CTRR' AND H.MALOP = 'K11' AND K.LANTHI = 1 AND K.KQUA = 'Khong Dat';

-- 5
SELECT H.MAHV, H.HO + ' ' + H.TEN AS HOTEN
FROM HOCVIEN H
JOIN KETQUATHI K ON H.MAHV = K.MAHV
WHERE H.MALOP = 'K' AND K.MAMH = 'CTRR'
GROUP BY H.MAHV, H.HO, H.TEN
HAVING COUNT(CASE WHEN K.KQUA = 'Dat' THEN 1 END) = 0; 
